pub mod proto {
    // Compile-include the protobuf code generated by tonic-build during building
    tonic::include_proto!("otp");

    /// Encoded file descriptor set for gRPC server reflection.
    /// This allows clients like Postman and grpcurl to auto-discover services.
    pub const FILE_DESCRIPTOR_SET: &[u8] =
        tonic::include_file_descriptor_set!("otp_descriptor");
}

pub mod otp_service;

pub use otp_service::OtpServiceImpl;
pub use proto::otp_service_server::OtpServiceServer;
