use crate::domain::{OtpError, TotpSetup};
use totp_rs::{Algorithm, Secret, TOTP};

/// Generates a new TOTP configuration including a secret key, provisioning URI, and Base64-encoded QR code.
pub fn generate_secret(issuer: &str, account_name: &str) -> Result<TotpSetup, OtpError> {
    // 1. Generate a secure random secret using the crate's built-in cryptographic generator
    let secret = Secret::generate_secret();
    let secret_bytes = secret
        .to_bytes()
        .map_err(|e| OtpError::TotpInitialization(e.to_string()))?;

    // 2. Encode secret bytes to a standard Base32 string (without padding)
    let secret_base32 = base32::encode(base32::Alphabet::Rfc4648 { padding: false }, &secret_bytes);

    // 3. Initialize the TOTP instance
    let totp = TOTP::new(
        Algorithm::SHA1,
        6,  // 6-digit OTP code
        0,  // Skew: increase this value if you want to allow code to be valid for longer
        30, // 30 seconds step/period
        secret_bytes,
        Some(issuer.to_string()),
        account_name.to_string(),
    )
    .map_err(|e| OtpError::TotpInitialization(e.to_string()))?;

    // 4. Extract provisioning URI and Base64 QR code representation
    let provisioning_uri = totp.get_url();
    let qr_code_base64_raw = totp
        .get_qr_base64()
        .map_err(|e| OtpError::QrGeneration(e))?;
    let qr_code_base64 = format!("data:image/png;base64,{}", qr_code_base64_raw);

    Ok(TotpSetup {
        secret: secret_base32,
        provisioning_uri,
        qr_code_base64,
    })
}

/// Verifies a 6-digit TOTP code against a Base32-encoded secret key.
pub fn verify_code(secret_base32: &str, code: &str) -> Result<bool, OtpError> {
    // 1. Validate the user input format (must be 6 numeric digits)
    if code.len() != 6 || !code.chars().all(|c| c.is_ascii_digit()) {
        return Err(OtpError::InvalidCode(
            "Code must be exactly 6 numeric digits".to_string(),
        ));
    }

    // 2. Parse the Base32 secret key into raw bytes
    let secret = Secret::Encoded(secret_base32.to_string());
    let secret_bytes = secret
        .to_bytes()
        .map_err(|e| OtpError::InvalidSecret(format!("Failed to parse Base32 secret: {}", e)))?;

    // 3. Initialize the TOTP instance with the parsed secret
    // Note: Issuer and account name are not used for verification code calculations.
    let totp = TOTP::new(
        Algorithm::SHA1,
        6,
        0, // Skew: increase this value if you want to allow code to be valid for longer
        30,
        secret_bytes,
        None,
        "".to_string(),
    )
    .map_err(|e| OtpError::TotpInitialization(e.to_string()))?;

    // 4. Verify code against current system time
    let is_valid = totp
        .check_current(code)
        .map_err(|e| OtpError::TotpInitialization(format!("System time error: {}", e)))?;

    Ok(is_valid)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_and_verify_otp() {
        let issuer = "TestIssuer";
        let account_name = "test@example.com";

        let setup = generate_secret(issuer, account_name).expect("Failed to generate secret");
        assert!(!setup.secret.is_empty(), "Secret should not be empty");
        assert!(
            setup.provisioning_uri.contains("secret="),
            "URI must contain secret"
        );
        assert!(
            setup.qr_code_base64.starts_with("data:image/png;base64,"),
            "QR must be base64 PNG data URI"
        );

        // Verify with the newly generated secret
        // Since we are verifying immediately, the code generated by TOTP now should match
        let secret = Secret::Encoded(setup.secret.clone());
        let secret_bytes = secret.to_bytes().unwrap();
        let totp = TOTP::new(
            Algorithm::SHA1,
            6,
            1,
            30,
            secret_bytes,
            None,
            "".to_string(),
        )
        .unwrap();
        let current_code = totp.generate_current().unwrap();

        let verify_result = verify_code(&setup.secret, &current_code).expect("Verification failed");
        assert!(
            verify_result,
            "Verification should succeed for current code"
        );
    }

    #[test]
    fn test_invalid_verification_code() {
        let issuer = "TestIssuer";
        let account_name = "test@example.com";

        let setup = generate_secret(issuer, account_name).expect("Failed to generate secret");

        // Invalid code characters
        let result = verify_code(&setup.secret, "12345a");
        assert!(result.is_err(), "Should fail for non-digit code");

        // Invalid code length
        let result = verify_code(&setup.secret, "12345");
        assert!(result.is_err(), "Should fail for short code");

        // Expired/wrong code
        let result = verify_code(&setup.secret, "999999").expect("Verification check failed");
        assert!(!result, "Should return false for incorrect code");
    }
}
